# Generated by Django 3.2.5 on 2021-10-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_record_voice_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='voice_record',
            field=models.FileField(upload_to='records'),
        ),
    ]
