# Generated by Django 3.2.5 on 2023-02-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_record_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
